In [166]:
import torch

from ansatz_utils.permutation_actions import permutation_sign, random_negative_permutation, random_positive_permutation, random_transposition

In [182]:
X = torch.randint(low=-10, high=10, size=(15, ))

In [183]:
xsort, asort = torch.sort(X, stable=True)
xsort

tensor([-9, -5, -4, -3, -2, -2, -2,  0,  1,  1,  2,  4,  5,  8,  8])

In [184]:
sign = permutation_sign(asort)
sign

tensor([1], dtype=torch.int32)

In [191]:
shuffle = random_transposition(15)# if sign == -1 else random_positive_permutation(15)

new_sign = permutation_sign(torch.argsort(xsort[shuffle], stable=True))
new_sign

tensor([-1], dtype=torch.int32)